services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desa_app
    volumes:
      - .:/var/www
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: desa_nginx
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: desa_db
    restart: always
    environment:
      MYSQL_DATABASE: desa
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
